groups:
  - name: gateway_tenant_device_alerts
    interval: 5s
    rules:
      - alert: TenantGatewaysOffline
        expr: offline_gateway_devices_total > 0
        for: 2s
        labels:
          severity: critical
        annotations:
          summary: "The tenant {{ $labels.tenant_name }} has offline gateway."
          description: |
            Gateway device offline:
            - Device: {{ $labels.device_name }}
            - Device ID: {{ $labels.device_id }}
            - Tenant: {{ $labels.tenant_name }}
            - Tenant ID: {{ $labels.tenant_id }}
            - Status: Offline for more than 2 minutes
