image: docker:git
services:
  - docker:dind

stages:
  # - lint
  # - test
  - build
  # - production

variables:
  IMAGE_NAME: registry.gitlab.com/yroomio/grms
  IMAGE_TAG: latest

# lint:
#   image: python:3.12-alpine
#   stage: lint
#   script:
#     - pip install black==24.4.2
#     - black . --check

# test:
#   stage: test
#   image: python:3.12
#   services:
#     - name: postgres:16-alpine
#       alias: postgres
#       variables:
#         POSTGRES_DB: roomio
#         POSTGRES_USER: runner
#         POSTGRES_PASSWORD: ""
#   variables:
#     DATABASE_NAME: roomio
#     DATABASE_USER: runner
#     DATABASE_PASSWORD: ""
#     DATABASE_HOST: postgres
#     DATABASE_PORT: 5432
#     POSTGRES_HOST_AUTH_METHOD: trust
#   script:
#     - pip install -r requirements.txt
#     - mkdir -p logs
#     - ./manage.py test

build:
  stage: build
  when: manual
  script:
    - echo $CI_REGISTRY_USER
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

# production:
#   stage: production
#   when: manual
#   image: python:3.12
#   only:
#     - Umarov
#   script:
#     - echo "$PROD_PRIVATE_KEY" >> publickey && chmod 600 publickey
#     - ssh -o "StrictHostKeyChecking=no" -i publickey $PROD_USER@$PROD_HOST -p $PROD_PORT "
#       cd /home/bakhodir/GRMS/;
#       git pull origin Umarov;
#       docker compose up --build web -d;"
