image: docker:git
services:
  - docker:dind

stages:
  # - lint
  # - test
  - build
  - production

variables:
  IMAGE_NAME: registry.gitlab.com/yroomio/grms
  IMAGE_TAG: latest

build:
  stage: build
  when: manual
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

production:
  stage: production
  when: manual
  image: alpine:latest
  only:
    - Umarov
  script:
    - apk add --no-cache openssh-client
    - echo "$PROD_PRIVATE_KEY" >> publickey && chmod 600 publickey
    - ssh -o "StrictHostKeyChecking=no" -i publickey $PROD_USER@$PROD_HOST -p $PROD_PORT "
      mkdir -p ~/GRMS;
      cd ~/GRMS;
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY";
      docker compose down &&
      docker compose pull &&
      docker compose up -d;
      "
