services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django
    command: >
      /bin/bash -c "
      python /app/manage.py migrate &&
      python /app/manage.py collectstatic --no-input &&
      supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    ports:
      - '8000:8000'
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - .:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - postgres

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    image: nginx:latest
    container_name: nginx
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - '9000:9000'
    depends_on:
      - web

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}


volumes:
  static_volume:
  media_volume:
  pg_data: