services:
  web:
    build: .
    container_name: django
    restart: always
    command: >
      /bin/bash -c "
      python /app/manage.py migrate &&
      python /app/manage.py collectstatic --no-input &&
      supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    ports:
      - "8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - .:/app
      - static_volume:/app/static/
      - media_volume:/app/media/

volumes:
  static_volume:
  media_volume:
  pg_data:
