[supervisord]
nodaemon=true

[program:django]
command=/usr/local/bin/gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:8000
directory=/app
stdout_logfile=/var/log/django/gunicorn.log
stderr_logfile=/var/log/django/gunicorn_error.log
autostart=true
autorestart=true

[program:django-background-task-mq]
command=/usr/local/bin/python manage.py mq
directory=/app
stdout_logfile=/var/log/supervisor/django-background-task-mq-stdout.log
stderr_logfile=/var/log/supervisor/django-background-task-mq-stderr.log
autostart=true
autorestart=true


[program:django-background-task-read-write-cpu-ram]
command=/usr/local/bin/python manage.py read_write_cpu_ram
directory=/app
stdout_logfile=/var/log/supervisor/django-background-task-read-write-cpu-ram-stdout.log
stderr_logfile=/var/log/supervisor/django-background-task-read-write-cpu-ram-stderr.log
autostart=true
autorestart=true


[program:check_attribute_server_scope]
command=/usr/local/bin/python manage.py check_attribute_server_scope
directory=/app
stdout_logfile=/var/log/supervisor/check_attribute_server_scope-stdout.log
stderr_logfile=/var/log/supervisor/check_attribute_server_scope-stderr.log
autostart=true
autorestart=true
