[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/dev/null

[program:django]
command=/usr/local/bin/gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:8000
directory=/app
stdout_logfile=/var/log/django/gunicorn.log
stderr_logfile=/var/log/django/gunicorn_error.log
autostart=true
autorestart=true

[program:mq]
command=/usr/local/bin/python manage.py mq
directory=/app
stdout_logfile=/var/log/supervisor/mq-stdout.log
stderr_logfile=/var/log/supervisor/mq-stderr.log
autostart=true
autorestart=true


[program:read_write_cpu_ram]
command=/usr/local/bin/python manage.py read_write_cpu_ram
directory=/app
stdout_logfile=/var/log/supervisor/read_write_cpu_ram-stdout.log
stderr_logfile=/var/log/supervisor/read_write_cpu_ram-stderr.log
autostart=true
autorestart=true


[program:active_attribute_server_scope]
command=/usr/local/bin/python manage.py active_attribute_server_scope
directory=/app
stdout_logfile=/var/log/supervisor/active_attribute_server_scope-stdout.log
stderr_logfile=/var/log/supervisor/active_attribute_server_scope-stderr.log
autostart=true
autorestart=true

[program:celery]
command=/usr/local/bin/celery -A config worker --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/celery-stdout.log
stderr_logfile=/var/log/supervisor/celery-stderr.log

[program:celery-beat]
command=/usr/local/bin/celery -A config beat --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/celery-beat-stdout.log
stderr_logfile=/var/log/supervisor/celery-beat-stderr.log

