# Generated by Django 5.0.4 on 2025-03-24 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0037_rename_type_roomhistory_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('enable', models.BooleanField(default=False, help_text='Designates whether this integration is enable.', verbose_name='enable')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_integration',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(models.F('name'), models.F('type'), models.F('tenant'), condition=models.Q(('is_active', True)), name='unique_integration_name_type_tenant_is_active'),
        ),
    ]
