# Generated by Django 5.0.4 on 2025-04-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('FIAS', 'FIAS'), ('hoteza', 'hoteza')], default='FIAS', max_length=100),
        ),
    ]
