# Generated by Django 5.0.4 on 2025-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_integration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="type",
            field=models.CharField(choices=[("fias", "Fias"), ("hoteza", "Hoteza"), ("mews", "Mews")], max_length=20),
        ),
    ]
