# Generated by Django 5.0.4 on 2025-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_integration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
