# Generated by Django 5.0.4 on 2026-05-04 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_alter_room_state_alter_roomhistory_state"),
        ("services", "0004_alter_integration_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="integration",
            name="unique_integration_name_type_tenant_is_active",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="type",
        ),
        migrations.AddField(
            model_name="integration",
            name="access_token",
            field=models.CharField(
                blank=True, help_text="For KeyCards", max_length=100, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                models.F("name"),
                models.F("tenant"),
                condition=models.Q(("is_active", True)),
                name="unique_integration_name_tenant_is_active",
            ),
        ),
    ]
