# Generated by Django 5.0.4 on 2026-05-04 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_alter_room_state_alter_roomhistory_state"),
        (
            "services",
            "0005_remove_integration_unique_integration_name_type_tenant_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="hotel_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="integration",
            name="name",
            field=models.CharField(
                choices=[("fias", "Fias"), ("hoteza", "Hoteza"), ("mews", "Mews")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration",
                to="main.tenant",
            ),
        ),
    ]
