# Generated by Django 5.0.4 on 2026-05-12 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_alter_room_state_alter_roomhistory_state"),
        ("services", "0006_integration_hotel_id_alter_integration_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integrator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="integration",
            name="unique_integration_name_tenant_is_active",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="name",
        ),
        migrations.AlterField(
            model_name="integration",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrator",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(model_name)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integrator",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(model_name)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="integrator",
            field=models.ForeignKey(
                db_column="integrator",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.integrator",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                models.F("integrator"),
                models.F("tenant"),
                condition=models.Q(("is_active", True)),
                name="unique_integration_integrator_tenant_is_active",
            ),
        ),
    ]
