# Generated by Django 5.0.4 on 2025-04-03 10:41

import core.utils.get_time
import core.utils.unix_timestamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
    ]
