# Generated by Django 5.0.4 on 2025-07-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_resetpassword_created_at_alter_role_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="additional_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
