# Generated by Django 5.0.4 on 2025-08-01 14:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_resetpassword_created_by_role_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"default_related_name": "users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
    ]
