# Generated by Django 5.0.4 on 2025-08-02 10:04

from functools import partial

import django.utils.timezone
from django.db import migrations, models

from main.convert_date import convert_to_timestamp, revert_to_bigint


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0008_alter_user_options_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=partial(convert_to_timestamp, table_name="users_users", field_name="date_joined"),
            reverse_code=partial(revert_to_bigint, table_name="users_users", field_name="date_joined"),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="date_joined",
                    field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
            ],
        ),
        migrations.RunPython(
            code=partial(convert_to_timestamp, table_name="users_users", field_name="last_login"),
            reverse_code=partial(revert_to_bigint, table_name="users_users", field_name="last_login"),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="last_login",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
            ],
        ),
    ]
