# Generated by Django 5.0.4 on 2025-08-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_date_joined_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resetpassword",
            options={"ordering": ("id",)},
        ),
    ]
