# Generated by Django 5.0.4 on 2025-10-28 09:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0052_remove_room_door_lock_id_and_more"),
        ("users", "0010_alter_resetpassword_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("is_active", True)),
                name="unique_user_email_is_active",
            ),
        ),
    ]
