# Generated by Django 5.0.4 on 2025-12-04 10:27

import core.utils.unix_timestamp
import django.db.models.deletion
import users.utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0054_alter_created_at_field_type"),
        ("users", "0011_alter_user_email_user_unique_user_email_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpassword",
            name="expires_at",
            field=core.utils.unix_timestamp.UnixTimeStampField(
                default=users.utils.fields.expires_hour, help_text="Unix timestamp when the reset token expires"
            ),
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="key",
            field=models.CharField(help_text="Unique token for password reset", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="user",
            field=models.ForeignKey(
                help_text="User who requested the password reset",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="additional_info",
            field=models.JSONField(blank=True, help_text="Additional role configuration stored as JSON", null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(help_text="Name of the role", max_length=255),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions granted to this role",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant (hotel/property) this role belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="main.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="additional_info",
            field=models.JSONField(blank=True, help_text="Additional user information stored as JSON", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer associated with this user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.customer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address used for authentication and communication", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the user",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, help_text="User's phone number", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The tenant (hotel/property) this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tenant",
            ),
        ),
    ]
