# Generated by Django 5.0.4 on 2026-04-07 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0056_delete_emailconfiguration"),
        ("users", "0012_alter_resetpassword_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="role",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant (hotel/property) this role belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="main.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)), fields=("name", "tenant"), name="unique_role_name_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)), fields=("name",), name="unique_role_name_no_tenant"
            ),
        ),
    ]
