# Generated by Django 5.0.4 on 2026-08-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_tenantgroup_tenant_group_and_more'),
        ('users', '0013_alter_role_unique_together_alter_role_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_group',
            field=models.ForeignKey(blank=True, help_text='Hotel chain this user manages. If set, the user may switch between all of its tenants.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.tenantgroup'),
        ),
    ]
