# Generated by Django 5.0.4 on 2025-11-30 14:44

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0053_guest_pms_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MewsConfiguration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec, editable=False, null=True
                    ),
                ),
                (
                    "updated_at",
                    core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
                ),
                (
                    "client_token",
                    models.CharField(help_text="Mews ClientToken (application identifier)", max_length=255),
                ),
                ("access_token", models.CharField(help_text="Mews AccessToken (property-specific)", max_length=255)),
                ("company_id", models.UUIDField(help_text="Mews Company ID")),
                (
                    "environment",
                    models.CharField(
                        choices=[("demo", "Demo"), ("production", "Production")],
                        default="production",
                        help_text="Mews environment",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Enable/disable Mews integration for this tenant"),
                ),
                (
                    "auto_sync",
                    models.BooleanField(default=True, help_text="Automatically sync reservations in real-time"),
                ),
                ("last_sync", models.DateTimeField(blank=True, help_text="Last successful sync timestamp", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mews_config",
                        to="main.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mews Configuration",
                "verbose_name_plural": "Mews Configurations",
                "db_table": "mews_configuration",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
