# prometheus.yml - Updated configuration
global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "django"
    static_configs:
      - targets: ["host.docker.internal:8000"] # host.docker.internal:8000
    scrape_interval: 30s
    scrape_timeout: 5s
    sample_limit: 50000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(offline_gateway_.*|django_.*|python_.*|up)"
        action: keep

  - job_name: "blackbox-https"
    metrics_path: /probe
    params:
      module: [https_relaxed]
    static_configs:
      - targets:
          - https://api.grms.room.io
          - https://grms.room.io
          - https://api.leto.tais.su
          - https://leto.tais.su
          - https://nodered.leto.tais.su
          - https://nodered-sber.leto.tais.su
          - https://grafana.leto.tais.su
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
