# Generated by Django 5.0.4 on 2026-07-28 18:47

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0063_tenant_has_access_ai"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec, null=True
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=128)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "netbird_peer_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("mesh_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "last_seen",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "enrolled_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "netbird_version",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("ssh_user", models.CharField(default="roomio-agent", max_length=64)),
                ("ssh_host_key", models.TextField(blank=True, null=True)),
                (
                    "install_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "token_expires_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "token_used_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "netbird_setup_key_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "netbird_setup_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_nodes",
                        to="main.device",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_nodes",
                        to="main.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fleet_node",
                "ordering": ("id",),
                "permissions": [
                    ("enroll_fleetnode", "Can issue install tokens for fleet nodes"),
                    ("terminal_fleetnode", "Can open a terminal on a fleet node"),
                    ("exec_fleetnode", "Can run commands on a fleet node"),
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FleetAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("token_issued", "Install token issued"),
                            ("bootstrap_served", "Bootstrap script served"),
                            ("bootstrap_rejected", "Bootstrap request rejected"),
                            ("peer_pinned", "NetBird peer pinned"),
                            ("peer_mismatch", "NetBird peer id mismatch"),
                            ("peer_deleted", "NetBird peer deleted"),
                            ("setup_key_created", "NetBird setup key created"),
                            ("setup_key_deleted", "NetBird setup key deleted"),
                            ("host_key_pinned", "SSH host key pinned"),
                            ("host_key_mismatch", "SSH host key mismatch"),
                            ("command_run", "Command executed"),
                            ("terminal_open", "Terminal session opened"),
                            ("terminal_close", "Terminal session closed"),
                            ("terminal_denied", "Terminal session denied"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="fleet.fleetnode",
                    ),
                ),
            ],
            options={
                "db_table": "fleet_audit_log",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="fleetnode",
            index=models.Index(fields=["code"], name="fleet_node_code_idx"),
        ),
        migrations.AddConstraint(
            model_name="fleetnode",
            constraint=models.UniqueConstraint(
                models.F("gateway"),
                condition=models.Q(("is_active", True)),
                name="unique_active_fleet_node_gateway",
            ),
        ),
        migrations.AddConstraint(
            model_name="fleetnode",
            constraint=models.UniqueConstraint(
                models.F("code"),
                condition=models.Q(("is_active", True)),
                name="unique_active_fleet_node_code",
            ),
        ),
        migrations.AddIndex(
            model_name="fleetauditlog",
            index=models.Index(
                fields=["node", "-created_at"], name="fleet_audit_node_ts_idx"
            ),
        ),
    ]
