# Generated by Django 5.0.4 on 2026-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fleetnode",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("enroll_fleetnode", "Can issue install tokens for fleet nodes"),
                    ("terminal_fleetnode", "Can open a terminal on a fleet node"),
                    ("exec_fleetnode", "Can run commands on a fleet node"),
                    ("upload_fleetnode", "Can upload files to a fleet node"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="fleetauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("token_issued", "Install token issued"),
                    ("bootstrap_served", "Bootstrap script served"),
                    ("bootstrap_rejected", "Bootstrap request rejected"),
                    ("peer_pinned", "NetBird peer pinned"),
                    ("peer_mismatch", "NetBird peer id mismatch"),
                    ("peer_deleted", "NetBird peer deleted"),
                    ("setup_key_created", "NetBird setup key created"),
                    ("setup_key_deleted", "NetBird setup key deleted"),
                    ("host_key_pinned", "SSH host key pinned"),
                    ("host_key_mismatch", "SSH host key mismatch"),
                    ("command_run", "Command executed"),
                    ("terminal_open", "Terminal session opened"),
                    ("terminal_close", "Terminal session closed"),
                    ("terminal_denied", "Terminal session denied"),
                    ("file_uploaded", "File uploaded"),
                    ("file_upload_failed", "File upload failed"),
                ],
                max_length=32,
            ),
        ),
    ]
