# Generated by Django 5.0.4 on 2026-09-02 07:05

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_alter_fleetnode_options_alter_fleetauditlog_action"),
        ("main", "0065_tenantgroup_tenant_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleetauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("token_issued", "Install token issued"),
                    ("bootstrap_served", "Bootstrap script served"),
                    ("bootstrap_rejected", "Bootstrap request rejected"),
                    ("peer_pinned", "NetBird peer pinned"),
                    ("peer_mismatch", "NetBird peer id mismatch"),
                    ("peer_deleted", "NetBird peer deleted"),
                    ("setup_key_created", "NetBird setup key created"),
                    ("setup_key_deleted", "NetBird setup key deleted"),
                    ("host_key_pinned", "SSH host key pinned"),
                    ("host_key_mismatch", "SSH host key mismatch"),
                    ("command_run", "Command executed"),
                    ("terminal_open", "Terminal session opened"),
                    ("terminal_close", "Terminal session closed"),
                    ("terminal_denied", "Terminal session denied"),
                    ("file_uploaded", "File uploaded"),
                    ("file_upload_failed", "File upload failed"),
                    ("job_started", "Bulk job started"),
                    ("job_cancelled", "Bulk job cancelled"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FleetJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec, null=True
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("params", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "started_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "finished_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_jobs",
                        to="main.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fleet_job",
                "ordering": ("-created_at",),
                "permissions": [
                    ("run_fleetjob", "Can run bulk actions across fleet nodes")
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FleetJobTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=core.utils.get_time.get_mil_sec,
                        editable=False,
                        null=True,
                    ),
                ),
                ("node_code", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("stdout", models.TextField(blank=True, null=True)),
                ("stderr", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "started_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "finished_at",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="fleet.fleetjob",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_tasks",
                        to="fleet.fleetnode",
                    ),
                ),
            ],
            options={
                "db_table": "fleet_job_task",
                "ordering": ("node_code",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="fleetjob",
            index=models.Index(
                fields=["tenant", "-created_at"], name="fleet_job_tenant_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fleetjobtask",
            index=models.Index(
                fields=["job", "status"], name="fleet_job_task_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fleetjobtask",
            constraint=models.UniqueConstraint(
                models.F("job"), models.F("node"), name="unique_fleet_job_task_node"
            ),
        ),
    ]
