### 

@device_id = 8031dcd8-c58b-46c2-ac4e-a46fea72b612


### get_list

GET {{BASE_URL}}/main/device/ HTTP/1.1
Authorization: Bearer {{access_token}}


### get_detail

GET {{BASE_URL}}/main/device/{{device_id}}/ HTTP/1.1
Authorization: Bearer {{access_token}}

> {%
  if (response.responseCode === 200) {
    client.global.set("device_detail", response.body);
    console.log("Saved: " + response.body);
  }
%}


### udpate_detail

PUT {{BASE_URL}}/main/device/{{device_id}}/ HTTP/1.1
Authorization: Bearer {{access_token}}

{
  "device_profile": "e5cbc6df-2b1e-41bd-9212-987f964a4563",
  "name": "a0:68:93:99:93:25",
  "status": 1,
  "type": "default"
}
