### 

GET {{BASE_URL}}/main/integration-settings/ HTTP/1.1
Authorization: Bearer {{access_token}}


### 

PUT {{BASE_URL}}/main/integration-settings/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "PMS_type": null,
  "hoteza": {
    "enable": true,
    "hotel_id": "327"
  },
  "integration_device": null,
  "is_active": null,
  "mews": {
    "access_token": "",
    "client_token": "",
    "enable": true,
    "environment": "production",
    "hotel_id": "1",
    "roomio_access_control": false,
    "send_tasks": false
  }
}
