# Generated by Django 5.0.4 on 2024-09-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_role_user_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
    ]
