global:
  resolve_timeout: 5m

route:
  group_by: [alertname]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m
  receiver: telegram

receivers:
- name: telegram
  telegram_configs:
  - bot_token: '7948736122:AAGdZSWxtjDOxnvt_fDdgjhyWXO2vnzdQjU'
    chat_id: -1002773769576
    send_resolved: true


