# Generated by Django 5.0.4 on 2026-09-17 11:23

import core.utils.get_time
import core.utils.unix_timestamp
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0066_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('updated_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True)),
                ('alarm_type', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('WARNING', 'Warning'), ('INDETERMINATE', 'Indeterminate')], max_length=16)),
                ('acknowledged', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('start_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('ack_ts', models.DateTimeField(blank=True, null=True)),
                ('clear_ts', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('propagate', models.BooleanField(default=False)),
                ('propagate_relation_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('propagate_to_owner', models.BooleanField(default=False)),
                ('propagate_to_tenant', models.BooleanField(default=False)),
                ('propagate_entity_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('assign_ts', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notified_clear_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alarms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='main.device')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='main.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='main.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alarms_alarm',
                'ordering': ('-start_ts',),
                'permissions': [('ack_alarm', 'Can acknowledge alarms'), ('clear_alarm', 'Can clear alarms'), ('assign_alarm', 'Can assign alarms')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('alarm_comment_type', models.CharField(choices=[('OTHER', 'Other'), ('SYSTEM', 'System')], default='OTHER', max_length=16)),
                ('comment', models.JSONField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alarms.alarm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alarms_alarm_comment',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmRuleState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('alarm_rule_type', models.CharField(max_length=255)),
                ('state', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rule_states', to='main.device')),
            ],
            options={
                'db_table': 'alarms_rule_state',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['tenant', 'cleared', '-start_ts'], name='ix_alarm_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['originator', '-start_ts'], name='ix_alarm_originator'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['alarm_type', '-start_ts'], name='ix_alarm_type'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['severity', '-start_ts'], name='ix_alarm_severity'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=django.contrib.postgres.indexes.GinIndex(fields=['propagate_entity_ids'], name='ix_alarm_propagate'),
        ),
        migrations.AddConstraint(
            model_name='alarm',
            constraint=models.UniqueConstraint(condition=models.Q(('cleared', False)), fields=('originator', 'alarm_type'), name='uniq_active_alarm_per_originator_type'),
        ),
        migrations.AddIndex(
            model_name='alarmcomment',
            index=models.Index(fields=['alarm', '-created_at'], name='ix_alarm_comment_alarm'),
        ),
        migrations.AddConstraint(
            model_name='alarmrulestate',
            constraint=models.UniqueConstraint(fields=('device', 'alarm_rule_type'), name='uniq_rule_state_device_type'),
        ),
    ]
