# Generated by Django 5.0.4 on 2026-10-05 10:06

import core.utils.get_time
import core.utils.unix_timestamp
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
        ('main', '0066_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('updated_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True)),
                ('alarm_type', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('create_rules', models.JSONField(default=dict)),
                ('clear_rule', models.JSONField(blank=True, null=True)),
                ('propagate', models.BooleanField(default=False)),
                ('propagate_relation_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('propagate_to_owner', models.BooleanField(default=False)),
                ('propagate_to_tenant', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('device_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rules', to='main.deviceprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rules', to='main.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alarms_alarm_rule',
                'ordering': ('alarm_type',),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='ix_alarm_rule_tenant'), models.Index(fields=['device_profile', 'enabled'], name='ix_alarm_rule_profile')],
            },
        ),
        migrations.AddConstraint(
            model_name='alarmrule',
            constraint=models.UniqueConstraint(fields=('device_profile', 'alarm_type'), name='uniq_alarm_rule_profile_type'),
        ),
    ]
