# Generated by Django 5.0.4 on 2025-02-13 08:26

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='access_manager.card')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_manager.staff')),
            ],
            options={
                'db_table': 'access_manager_staff_cards',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
