# Generated by Django 5.0.4 on 2025-02-14 11:21

import time
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import core.utils.unix_timestamp


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0002_staffcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppublicspace',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='grouproom',
            name='staff',
        ),
        migrations.CreateModel(
            name='GroupStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_manager.group')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='access_manager.staff')),
            ],
            options={
                'db_table': 'access_manager_group_staff',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
