# Generated by Django 5.0.4 on 2025-02-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0003_remove_grouppublicspace_staff_remove_grouproom_staff_and_more'),
        ('main', '0030_device_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppublicspace',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_public_space', to='access_manager.group'),
        ),
        migrations.AlterField(
            model_name='grouppublicspace',
            name='public_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_public_space', to='access_manager.publicspace'),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_room', to='access_manager.group'),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_room', to='main.room'),
        ),
        migrations.AlterUniqueTogether(
            name='publicspace',
            unique_together={('name', 'tenant')},
        ),
    ]
