# Generated by Django 5.0.4 on 2025-02-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0004_alter_grouppublicspace_group_and_more'),
        ('main', '0030_device_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_card',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('number', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
    ]
