# Generated by Django 5.0.4 on 2025-02-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0005_remove_card_unique_card_alter_card_unique_together_and_more'),
        ('main', '0031_publicspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpublicspace',
            name='public_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publicspace'),
        ),
        migrations.AlterField(
            model_name='grouppublicspace',
            name='public_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_public_space', to='main.publicspace'),
        ),
        migrations.DeleteModel(
            name='PublicSpace',
        ),
    ]
