# Generated by Django 5.0.4 on 2025-02-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0006_alter_guestpublicspace_public_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_manager.group'),
        ),
        migrations.DeleteModel(
            name='GroupStaff',
        ),
    ]
