# Generated by Django 5.0.4 on 2025-04-03 10:41

import core.utils.get_time
import core.utils.unix_timestamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0007_staff_group_delete_groupstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grouppublicspace',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='guestpublicspace',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='needsyncdevice',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='staffcard',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
    ]
