# Generated by Django 5.0.4 on 2025-04-28 09:24

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0009_alter_card_updated_at_alter_group_updated_at'),
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_manager.card')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guest')),
            ],
            options={
                'db_table': 'access_manager_guest_cards',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='guestcard',
            constraint=models.UniqueConstraint(models.F('guest'), models.F('card'), condition=models.Q(('is_active', True)), name='unique_active_guest_card'),
        ),
    ]
