# Generated by Django 5.0.4 on 2025-05-14 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0010_guestcard_guestcard_unique_active_guest_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[(2, 'HOUSEKEEPING'), (3, 'ENGINEERING'), (4, 'MASTER CARD')], default=2),
        ),
        migrations.AddConstraint(
            model_name='staffcard',
            constraint=models.UniqueConstraint(models.F('staff'), models.F('card'), condition=models.Q(('is_active', True)), name='unique_active_staff_card'),
        ),
    ]
