# Generated by Django 5.0.4 on 2025-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0011_alter_group_group_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.IntegerField(choices=[(2, 'HOUSEKEEPING'), (3, 'ENGINEERING'), (4, 'MASTER_CARD')], help_text='Must be one of: HOUSEKEEPING, ENGINEERING, MASTER_CARD'),
        ),
    ]
