# Generated by Django 5.0.4 on 2025-06-04 06:16

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0012_alter_group_group_type'),
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.CharField(max_length=200)),
                ('event_ts', models.DateTimeField()),
                ('access_group', models.IntegerField(choices=[(0, 'DENIED'), (1, 'GUEST'), (2, 'HOUSEKEEPING'), (3, 'ENGINEERING'), (4, 'MASTER_CARD'), (5, 'FAILED')], help_text='Must be one of: HOUSEKEEPING, ENGINEERING, MASTER_CARD')),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.device')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_logs', to='main.guest')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_logs', to='access_manager.staff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_manager_card_logs',
                'ordering': ['-event_ts'],
                'abstract': False,
            },
        ),
    ]
