# Generated by Django 5.0.4 on 2025-06-06 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0013_cardlog'),
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guestcard',
            name='unique_active_guest_card',
        ),
        migrations.AddConstraint(
            model_name='guestcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('card',), name='unique_card_active'),
        ),
    ]
