# Generated by Django 5.0.4 on 2025-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0014_remove_guestcard_unique_active_guest_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
