# Generated by Django 5.0.4 on 2025-06-23 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0016_card_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffcard',
            name='unique_active_staff_card',
        ),
        migrations.AddConstraint(
            model_name='staffcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('card',), name='unique_active_staff_card'),
        ),
    ]
