# Generated by Django 5.0.4 on 2025-07-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0018_carddeviceslot'),
        ('main', '0040_publicspace_accessible_for_guest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carddeviceslot',
            unique_together={('device', 'card_number'), ('device', 'slot')},
        ),
    ]
