# Generated by Django 5.0.4 on 2025-07-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0019_alter_carddeviceslot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_manager.card'),
        ),
    ]
