# Generated by Django 5.0.4 on 2025-07-04 12:32

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0020_alter_staffcard_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='needsyncdevice',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
        migrations.AddField(
            model_name='needsyncdevice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
