# Generated by Django 5.0.4 on 2025-07-30 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_manager", "0021_needsyncdevice_updated_at_needsyncdevice_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guestpublicspace",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(model_name)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
