# Generated by Django 5.0.4 on 2025-12-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_manager", "0022_guestpublicspace_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestcard",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
