# Generated by Django 5.0.4 on 2026-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_manager", "0024_timescaledb_card_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_pwd",
            field=models.BooleanField(default=False),
        ),
    ]
