# Generated by Django 5.0.4 on 2026-08-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0025_card_is_pwd'),
        ('main', '0065_tenantgroup_tenant_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_groups', to='main.tenant'),
        ),
    ]
