# Generated by Django 5.0.4 on 2024-07-11 11:33

import core.utils.unix_timestamp
import time
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tskv",
            name="ts",
            field=core.utils.unix_timestamp.UnixTimeStampField(
                default=time.time, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tskvlatest",
            name="ts",
            field=core.utils.unix_timestamp.UnixTimeStampField(
                default=time.time, null=True
            ),
        ),
    ]
