# Generated by Django 5.0.4 on 2024-09-23 13:19

import core.utils.unix_timestamp
import time
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0003_relation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPCMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
                ("additional_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "shuttle_rpcmessage",
            },
        ),
    ]
