# Generated by Django 5.0.4 on 2024-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0004_controllerfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPCMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('additional_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shuttle_rpc_message',
            },
        ),
    ]
