# Generated by Django 5.0.4 on 2024-11-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0005_controllerfile_controller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributekv',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='controller',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='controllerfile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ('id',)},
        ),
    ]
