# Generated by Django 5.0.4 on 2024-12-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0007_relation_updated_at_relation_updated_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tskvdictionary',
            unique_together={('key', 'key_id')},
        ),
    ]
