### Get All Resource Access Tokens

POST {{BASE_URL}}/resourceAccessTokens/getAll HTTP/1.1

{
  "AccessToken": "{{AccessToken}}",
  "ActivityStates": [
    "Active"
  ],
  "Client": "{{Client}}",
  "ClientToken": "{{ClientToken}}",
  "Limitation": {
    "Count": 10
  },
  "ServiceOrderIds": [
    "9bf29e03-e70c-4408-9c74-b3710085aa6d",
    "44edfae1-cf1a-4e2a-9c2b-b3a900e72ac6",
    "3a1b9b54-0f52-4e9f-b220-b3ae00afd27e",
    "1e8ddba0-d656-4405-b631-b3ae00860021",
    "adc61dfa-ba6c-47b2-a83c-b3ad009508f3",
    "d9cf3f6e-44ef-481d-a906-b3ab00f23669",
    "c924094f-f02f-4d9c-a4c8-b3ad00d03f59"
  ],
  "UpdatedUtc": {
    "EndUtc": "2025-12-15T12:00:00Z",
    "StartUtc": "2025-12-10T10:31:00Z"
  }
}


### Create Resource Access Token

POST {{BASE_URL}}/resourceAccessTokens/add HTTP/1.1

{
  "AccessToken": "{{AccessToken}}",
  "Client": "{{Client}}",
  "ClientToken": "{{ClientToken}}",
  "ResourceAccessTokenParameters": [
    {
      "Permissions": {
        "Bed": {
          "Value": true
        },
        "Building": {
          "Value": false
        },
        "Floor": {
          "Value": false
        },
        "Room": {
          "Value": true
        }
      },
      "ServiceOrderId": "c924094f-f02f-4d9c-a4c8-b3ad00d03f59",
      "Type": "RfidTag",
      "ValidityEndUtc": "2025-12-15T12:00:00Z",
      "ValidityStartUtc": "2025-12-11T14:00:00Z",
      "Value": "1234"
    }
  ]
}


### Delete Resource Access Token

POST {{BASE_URL}}/resourceAccessTokens/delete HTTP/1.1

{
  "AccessToken": "{{AccessToken}}",
  "Client": "{{Client}}",
  "ClientToken": "{{ClientToken}}",
  "Ids": [
    "ba1798f5-2704-4583-bb62-b3af00ae17eb"
  ]
}
