# Generated by Django 5.0.4 on 2024-05-06 04:54

import core.fields.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.fields.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('additional_info', models.CharField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('address2', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'main_tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.fields.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_data', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('isolated_tb_core', models.BooleanField(blank=True, null=True)),
                ('isolated_tb_rule_engine', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_tenant_profile',
            },
        ),
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.fields.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
            ],
            options={
                'db_table': 'main_admin_settings',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tenantprofile'),
        ),
    ]
