# Generated by Django 5.0.4 on 2024-05-07 08:56

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
            ],
            options={
                'db_table': 'main_email_configuration',
                'default_related_name': 'email_configurations',
            },
        ),
    ]
