# Generated by Django 5.0.4 on 2024-05-21 11:42

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_emailconfiguration_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("address", models.CharField(blank=True, null=True)),
                ("address2", models.CharField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zip", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.UUIDField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "main_customer",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("device_data", models.JSONField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.customer"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "main_device",
            },
        ),
        migrations.CreateModel(
            name="AttributeKv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("entity_type", models.CharField(max_length=255)),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("CLIENT_SCOPE", "CLIENT_SCOPE"),
                            ("SERVER_SCOPE", "SERVER_SCOPE"),
                            ("SHARED_SCOPE", "SHARED_SCOPE"),
                        ],
                        default="SERVER_SCOPE",
                        max_length=255,
                    ),
                ),
                ("attribute_key", models.CharField(max_length=255)),
                ("bool_v", models.BooleanField(blank=True, null=True)),
                ("str_v", models.CharField(blank=True, max_length=255, null=True)),
                ("long_v", models.BigIntegerField(blank=True, null=True)),
                ("dbl_v", models.FloatField(blank=True, null=True)),
                ("json_v", models.TextField(blank=True, null=True)),
                ("last_update_ts", models.BigIntegerField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.device"
                    ),
                ),
            ],
            options={
                "db_table": "main_attribute_kv",
            },
        ),
        migrations.CreateModel(
            name="DeviceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("image", models.CharField(blank=True, max_length=1000000, null=True)),
                (
                    "transport_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provision_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("profile_data", models.JSONField(blank=True, null=True)),
                ("description", models.CharField(blank=True, null=True)),
                ("is_default", models.BooleanField(blank=True, null=True)),
                (
                    "default_queue_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provision_device_key",
                    models.CharField(blank=True, null=True, unique=True),
                ),
                ("external_id", models.UUIDField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "main_device_profile",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="device_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.deviceprofile"
            ),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("check_in_out_address", models.IntegerField(blank=True, null=True)),
                ("check_in_value", models.IntegerField(blank=True, null=True)),
                ("check_out_value", models.IntegerField(blank=True, null=True)),
                ("reserver_value", models.IntegerField(blank=True, null=True)),
                (
                    "app_server_sip_server_enable",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "app_server_sip_account_num",
                    models.IntegerField(blank=True, null=True),
                ),
                ("vip_status_address", models.IntegerField(blank=True, null=True)),
                ("vip_status_on_value", models.IntegerField(blank=True, null=True)),
                ("vip_status_off_value", models.IntegerField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "main_room_type",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                (
                    "updated_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, null=True
                    ),
                ),
                ("room_number", models.IntegerField()),
                ("floor", models.CharField(max_length=255)),
                ("block", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("CheckedIn", "CheckedIn"),
                            ("Occupied", "Occupied"),
                            ("DoNotDistrub", "DoNotDistrub"),
                            ("MakeUpRoom", "MakeUpRoom"),
                        ],
                        default="Available",
                        max_length=255,
                    ),
                ),
                ("public_area_id", models.IntegerField(blank=True, null=True)),
                ("pan_id", models.CharField(blank=True, max_length=255, null=True)),
                ("building", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "door_lock_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.device",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(model_name)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "main_room",
            },
        ),
    ]
