# Generated by Django 5.0.4 on 2024-05-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device_roomtype_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={},
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='main_room_type',
        ),
    ]
