# Generated by Django 5.0.4 on 2024-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("main", "0005_alter_attributekv_entity_dashboard_and_more"),
	]

	operations = [
		migrations.AlterModelOptions(
			name="widgettype",
			options={
				"ordering": ["created_at"],
			},
		),
		migrations.AddField(
			model_name="room",
			name="status",
			field=models.CharField(choices=[("ON", "on"), ("OFF", "off")], default="OFF", max_length=255),
		),
	]
