# Generated by Django 5.0.4 on 2024-07-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_room_status_dashboard_roomtype_dashboard_widgettype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="block",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.IntegerField(),
        ),
    ]
