# Generated by Django 5.0.4 on 2024-07-30 09:53

import time
import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.utils.unix_timestamp


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_emailconfiguration_frontend_host_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("lastname", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "birthday",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "check_in",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "check_out",
                    core.utils.unix_timestamp.UnixTimeStampField(blank=True, null=True),
                ),
                (
                    "auto_check_out",
                    models.BooleanField(default=False),
                ),
                (
                    "reservation_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guests",
                        to="main.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.tenant"),
                ),
            ],
            options={
                "db_table": "main_guest",
                "ordering": ["created_at"],
            },
        ),
    ]
