# Generated by Django 5.0.4 on 2024-08-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_device_is_active_alter_device_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecredentials',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='main.device'),
        ),
    ]
