# Generated by Django 5.0.4 on 2024-08-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_devicecredentials_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
