# Generated by Django 5.0.4 on 2024-10-09 13:53

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deviceprofile_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('updated_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, null=True)),
                ('number', models.IntegerField()),
                ('floor', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('Available', 'Available'), ('CheckedIn', 'CheckedIn'), ('Occupied', 'Occupied'), ('DoNotDisturb', 'DoNotDisturb'), ('MakeUpRoom', 'MakeUpRoom')], default='Available', max_length=255)),
                ('public_area_id', models.IntegerField(blank=True, null=True)),
                ('pan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('door_lock_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('ON', 'on'), ('OFF', 'off')], default='OFF', max_length=255)),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.roomhistory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.roomtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_room_history',
                'default_related_name': 'room_history',
            },
        ),
    ]
