# Generated by Django 5.0.4 on 2024-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
