# Generated by Django 5.0.4 on 2024-10-15 11:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_dashboard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guests', to='main.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'CheckedIn'), (2, 'Occupied'), (3, 'DoNotDisturb'), (4, 'MakeUpRoom')]), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='roomhistory',
            name='state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'CheckedIn'), (2, 'Occupied'), (3, 'DoNotDisturb'), (4, 'MakeUpRoom')]), default=list, size=None),
        ),
    ]
