# Generated by Django 5.0.4 on 2024-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_guest_room_alter_room_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
