# Generated by Django 5.0.4 on 2024-11-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_room_unique_together_alter_room_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'tenant')},
        ),
    ]
