# Generated by Django 5.0.4 on 2024-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('title', 'tenant')},
        ),
    ]
