# Generated by Django 5.0.4 on 2024-12-09 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_roomtype_title_alter_roomtype_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('number', 'floor', 'block', 'tenant'), name='unique_active_room'),
        ),
    ]
