# Generated by Django 5.0.4 on 2025-01-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_deviceprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main.deviceprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='deviceprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name', 'tenant'), name='unique_active_device_profile'),
        ),
    ]
