# Generated by Django 5.0.4 on 2025-01-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_deviceprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsettings',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='devicecredentials',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='emailconfiguration',
            options={'default_related_name': 'email_configurations', 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='roomhistory',
            options={'default_related_name': 'room_history', 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tenantprofile',
            options={'ordering': ('id',)},
        ),
    ]
