# Generated by Django 5.0.4 on 2025-01-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('main', '0029_alter_adminsettings_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card'),
        ),
    ]
