# Generated by Django 5.0.4 on 2025-02-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0001_initial'),
        ('main', '0029_alter_adminsettings_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_manager.card'),
        ),
    ]
