# Generated by Django 5.0.4 on 2025-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_publicspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicspace',
            name='block',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicspace',
            name='floor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
