# Generated by Django 5.0.4 on 2025-03-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_publicspace_block_publicspace_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicspace',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.device'),
        ),
    ]
