# Generated by Django 5.0.4 on 2025-03-04 09:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_manager', '0007_staff_group_delete_groupstaff'),
        ('main', '0033_alter_publicspace_device'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_active_device',
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('tenant'), condition=models.Q(('is_active', True)), name='unique_device_name_tenant_is_active'),
        ),
    ]
