# Generated by Django 5.0.4 on 2025-03-06 13:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_device_unique_active_device_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviceprofile',
            name='unique_active_device_profile',
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('tenant'), name='unique_dashboard_title_tenant'),
        ),
        migrations.AddConstraint(
            model_name='deviceprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('tenant'), condition=models.Q(('active', True)), name='unique_active_device_profile'),
        ),
    ]
