# Generated by Django 5.0.4 on 2025-03-10 08:37

import django.contrib.postgres.fields
import main.utils.default_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_deviceprofile_unique_active_device_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'CheckedIn'), (2, 'Occupied'), (3, 'Reserved'), (4, 'MakeUpRoom')]), default=main.utils.default_state.default_state, size=None),
        ),
        migrations.AlterField(
            model_name='roomhistory',
            name='state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'CheckedIn'), (2, 'Occupied'), (3, 'Reserved'), (4, 'MakeUpRoom')]), default=list, size=None),
        ),
    ]
