# Generated by Django 5.0.4 on 2025-03-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_room_state_alter_roomhistory_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomhistory',
            old_name='type',
            new_name='room_type',
        ),
        migrations.AddField(
            model_name='roomhistory',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomhistory',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
            preserve_default=False,
        ),
    ]
