# Generated by Django 5.0.4 on 2025-04-03 10:41

import core.utils.get_time
import core.utils.unix_timestamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_type_roomhistory_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='devicecredentials',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='publicspace',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='roomhistory',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='widgettype',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
    ]
