# Generated by Django 5.0.4 on 2025-04-09 07:12

import core.utils.get_time
import core.utils.unix_timestamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_adminsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
        migrations.AlterField(
            model_name='roomhistory',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
    ]
