# Generated by Django 5.0.4 on 2025-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicspace',
            name='accessible_for_guest',
            field=models.BooleanField(default=False),
        ),
    ]
