# Generated by Django 5.0.4 on 2025-07-03 11:10

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_publicspace_accessible_for_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicspace',
            name='device',
        ),
        migrations.CreateModel(
            name='DevicePublicSpaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
                ('public_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publicspace')),
            ],
            options={
                'db_table': 'main_device_public_spaces',
                'ordering': ('id',),
                'abstract': False,
                'default_related_name': 'device_public_spaces',
                'unique_together': {('device', 'public_space')},
            },
        ),
    ]
