# Generated by Django 5.0.4 on 2025-07-07 05:34

import core.utils.get_time
import core.utils.unix_timestamp
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_publicspace_device_devicepublicspaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypePublicSpaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True)),
                ('public_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publicspace')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roomtype')),
            ],
            options={
                'db_table': 'main_room_type_public_spaces',
                'ordering': ('id',),
                'abstract': False,
                'default_related_name': 'room_type_public_spaces',
                'unique_together': {('room_type', 'public_space')},
            },
        ),
    ]
