# Generated by Django 5.0.4 on 2025-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_roomtypepublicspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="public_spaces",
            field=models.ManyToManyField(blank=True, through="main.RoomTypePublicSpaces", to="main.publicspace"),
        ),
    ]
