# Generated by Django 5.0.4 on 2025-07-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_roomtype_public_spaces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomtype",
            name="public_spaces",
        ),
    ]
