# Generated by Django 5.0.4 on 2025-07-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_remove_roomtype_public_spaces"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={"ordering": ("id",), "permissions": [("view_dashboardtype", "Can view dashboard types")]},
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"ordering": ("id",), "permissions": [("add_devicefromconf", "Can add device from conf")]},
        ),
        migrations.AlterModelOptions(
            name="guest",
            options={
                "ordering": ["created_at"],
                "permissions": [("change_guestmoveroom", "Can change guest move room")],
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("add_roomfromconf", "Can add room from conf"),
                    ("view_roomstatus", "Can view room status"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("view_alarmsettings", "Can view alarms"),
                    ("change_alarmsettings", "Can change alarms"),
                    ("view_generalsettings", "Can view general settings"),
                    ("change_generalsettings", "Can change general settings"),
                    ("view_integrationsettings", "Can view integration settings"),
                    ("change_integrationsettings", "Can change integration settings"),
                ],
            },
        ),
    ]
