# Generated by Django 5.0.4 on 2025-07-30 16:27

from functools import partial

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from main.convert_date import convert_to_timestamp, revert_to_bigint


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_prepare_emailconfiguration_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(model_name)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            code=partial(convert_to_timestamp, table_name="main_tenant", field_name="created_at"),
            reverse_code=partial(revert_to_bigint, table_name="main_tenant", field_name="created_at"),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="tenant",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
    ]
