# Generated by Django 5.0.4 on 2025-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_adminsettings_updated_at_adminsettings_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="additional_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
