# Generated by Django 5.0.4 on 2025-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_room_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="roomhistory",
            name="number",
            field=models.CharField(max_length=100),
        ),
    ]
