# Generated by Django 5.0.4 on 2025-10-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_room_label_alter_room_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="door_lock_id",
        ),
        migrations.RemoveField(
            model_name="roomhistory",
            name="door_lock_id",
        ),
        migrations.AddField(
            model_name="room",
            name="door_lock_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_door_lock_room",
                to="main.device",
            ),
        ),
        migrations.AddField(
            model_name="roomhistory",
            name="door_lock_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_door_lock_device_history",
                to="main.device",
            ),
        ),
    ]
