# Generated by Django 5.0.4 on 2025-12-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_remove_room_door_lock_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailConfiguration",
        ),
    ]
