# Generated by Django 5.0.4 on 2025-11-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_remove_room_door_lock_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="pms_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
