# Generated by Django 5.0.4 on 2025-12-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_guest_pms_id"),
    ]

    operations = [
        # Convert created_at from bigint (unix timestamp in milliseconds) to timestamp with time zone
        # Only if the column is currently bigint
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Check if the column is bigint
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'main_tenant'
                        AND column_name = 'created_at'
                        AND data_type = 'bigint'
                    ) THEN
                        -- Convert bigint to timestamp
                        ALTER TABLE main_tenant
                        ALTER COLUMN created_at TYPE timestamp with time zone
                        USING to_timestamp(created_at / 1000.0);
                    END IF;
                END $$;
                """,
            reverse_sql="""
                DO $$
                BEGIN
                    -- Check if the column is timestamp
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'main_tenant'
                        AND column_name = 'created_at'
                        AND data_type = 'timestamp with time zone'
                    ) THEN
                        -- Convert timestamp back to bigint
                        ALTER TABLE main_tenant
                        ALTER COLUMN created_at TYPE bigint
                        USING (EXTRACT(EPOCH FROM created_at) * 1000)::bigint;
                    END IF;
                END $$;
                """,
        ),
    ]
