# Generated by Django 5.0.4 on 2025-12-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0054_alter_created_at_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="checkout_by",
            field=models.CharField(
                blank=True, choices=[("roomio", "Roomio"), ("pms", "PMS")], max_length=50, null=True
            ),
        ),
    ]
