# Generated by Django 5.0.4 on 2025-12-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0055_guest_checkout_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailConfiguration",
        ),
    ]
