# Generated by Django 5.0.4 on 2026-04-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0056_delete_emailconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="main.tenant",
            ),
        ),
    ]
