# Generated by Django 5.0.4 on 2026-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_alter_room_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="is_reservation",
            field=models.BooleanField(default=False),
        ),
    ]
