# Generated by Django 5.0.4 on 2026-04-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_alter_room_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
