# Generated by Django 5.0.4 on 2026-04-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0058_alter_tenant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="engineering_dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engineering_room_types",
                to="main.dashboard",
            ),
        ),
    ]
