# Generated by Django 5.0.4 on 2026-04-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0059_roomtype_engineering_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="is_reservation",
            field=models.BooleanField(default=False),
        ),
    ]
