# Generated by Django 5.0.4 on 2026-04-24 11:15

import django.contrib.postgres.fields
import main.utils.default_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0060_guest_is_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="state",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (0, "Available"),
                        (1, "CheckedIn"),
                        (2, "Occupied"),
                        (3, "DoNotDisturb"),
                        (4, "MakeUpRoom"),
                        (5, "Reserved"),
                    ]
                ),
                default=main.utils.default_state.default_state,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="roomhistory",
            name="state",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (0, "Available"),
                        (1, "CheckedIn"),
                        (2, "Occupied"),
                        (3, "DoNotDisturb"),
                        (4, "MakeUpRoom"),
                        (5, "Reserved"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
