# Generated by Django 5.0.4 on 2026-05-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_alter_room_state_alter_roomhistory_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomhistory",
            name="door_lock_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_door_lock_device_history",
                to="main.device",
            ),
        ),
    ]
