# Generated by Django 5.0.4 on 2026-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_alter_roomhistory_door_lock_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="has_access_ai",
            field=models.BooleanField(default=False),
        ),
    ]
