# Generated by Django 5.0.4 on 2026-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_tenant_has_access_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
