# Generated by Django 5.0.4 on 2026-09-24 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0065_tenantgroup_tenant_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("view_alarmsettings", "Can view alarms"),
                    ("change_alarmsettings", "Can change alarms"),
                    ("view_generalsettings", "Can view general settings"),
                    ("change_generalsettings", "Can change general settings"),
                    ("view_integrationsettings", "Can view integration settings"),
                    ("change_integrationsettings", "Can change integration settings"),
                    ("unlock_user", "Can unlock user"),
                ],
            },
        ),
    ]
