# Generated by Django 5.0.4 on 2026-09-29 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('created_at',), 'permissions': [('change_guestmoveroom', 'Can change guest move room')]},
        ),
        migrations.AlterModelOptions(
            name='widgettype',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='checkout_by',
            new_name='check_out_source',
        ),
        migrations.AddField(
            model_name='guest',
            name='check_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='check_in_source',
            field=models.CharField(blank=True, choices=[('roomio', 'Roomio'), ('pms', 'PMS'), ('auto', 'Auto')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='check_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out_source',
            field=models.CharField(blank=True, choices=[('roomio', 'Roomio'), ('pms', 'PMS'), ('auto', 'Auto')], max_length=50, null=True),
        ),
    ]
