# Generated by Django 5.0.4 on 2026-09-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_guest_options_alter_widgettype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_source',
            field=models.CharField(blank=True, choices=[('roomio', 'Roomio'), ('mews', 'Mews'), ('hoteza', 'Hoteza'), ('fias', 'FIAS'), ('auto', 'Auto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out_source',
            field=models.CharField(blank=True, choices=[('roomio', 'Roomio'), ('mews', 'Mews'), ('hoteza', 'Hoteza'), ('fias', 'FIAS'), ('auto', 'Auto')], max_length=50, null=True),
        ),
    ]
