# Generated by Django 5.0.4 on 2024-06-10 11:48

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0006_alter_widgettype_options_room_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TsKvDictionary",
            fields=[
                ("key", models.CharField(max_length=255)),
                (
                    "key_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
            ],
            options={
                "db_table": "shuttle_ts_kv_dictionary",
            },
        ),
        migrations.CreateModel(
            name="TsKv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True),
                ),
                ("key", models.IntegerField()),
                ("bool_v", models.BooleanField(blank=True, null=True)),
                ("str_v", models.CharField(blank=True, max_length=255, null=True)),
                ("long_v", models.BigIntegerField(blank=True, null=True)),
                ("dbl_v", models.FloatField(blank=True, null=True)),
                ("json_v", models.JSONField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="main.device"),
                ),
            ],
            options={
                "db_table": "shuttle_ts_kv",
                "ordering": ("id",),
                "abstract": False,
                "unique_together": {("entity", "key", "created_at")},
            },
        ),
        migrations.CreateModel(
            name="TsKvLatest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True),
                ),
                ("key", models.IntegerField()),
                ("bool_v", models.BooleanField(blank=True, null=True)),
                ("str_v", models.CharField(blank=True, max_length=255, null=True)),
                ("long_v", models.BigIntegerField(blank=True, null=True)),
                ("dbl_v", models.FloatField(blank=True, null=True)),
                ("json_v", models.JSONField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="main.device"),
                ),
            ],
            options={
                "db_table": "shuttle_ts_kv_latest",
                "ordering": ("id",),
                "abstract": False,
                "unique_together": {("entity", "key")},
            },
        ),
    ]
