# Generated by Django 5.0.4 on 2024-07-11 14:09

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_devicecredentials"),
        ("shuttle", "0002_alter_tskv_ts_alter_tskvlatest_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                ("from_type", models.CharField(max_length=255)),
                ("to_type", models.CharField(max_length=255)),
                ("relation_type_group", models.CharField(max_length=255)),
                ("relation_type", models.CharField(max_length=255)),
                ("additional_info", models.CharField(blank=True, null=True)),
                (
                    "from_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_relations",
                        to="main.device",
                    ),
                ),
                (
                    "to_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_relations",
                        to="main.device",
                    ),
                ),
            ],
            options={
                "db_table": "shuttle_relation",
                "unique_together": {
                    (
                        "from_id",
                        "from_type",
                        "relation_type_group",
                        "relation_type",
                        "to_id",
                        "to_type",
                    )
                },
            },
        ),
    ]
