# Generated by Django 5.0.4 on 2024-11-21 09:32

import core.utils.files
import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_guest_additional_info_guest_language_guest_title'),
        ('shuttle', '0004_rpcmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('updated_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, null=True)),
                ('content', models.FileField(upload_to=core.utils.files.controller_file)),
                ('file_type', models.CharField(default='firmware', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shuttle_controller_file',
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, editable=False, null=True)),
                ('updated_at', core.utils.unix_timestamp.UnixTimeStampField(default=time.time, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttle.controllerfile')),
            ],
            options={
                'db_table': 'shuttle_controller',
            },
        ),
    ]
