# Generated by Django 5.0.4 on 2025-03-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0008_alter_tskvdictionary_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tskvlatest',
            name='key',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.DO_NOTHING, to='shuttle.tskvdictionary'),
        ),
    ]
