# Generated by Django 5.0.4 on 2025-04-01 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0009_alter_tskvlatest_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tskv',
            name='key',
            field=models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.DO_NOTHING, to='shuttle.tskvdictionary'),
        ),
    ]
