# Generated by Django 5.0.4 on 2025-04-03 10:41

import core.utils.get_time
import core.utils.unix_timestamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0010_alter_tskv_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekv',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='controllerfile',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tskv',
            name='ts',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
        migrations.AlterField(
            model_name='tskvlatest',
            name='ts',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
    ]
