# Generated by Django 5.0.4 on 2025-04-09 07:12

import core.utils.get_time
import core.utils.unix_timestamp
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0011_alter_attributekv_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekv',
            name='last_update_ts',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec),
        ),
        migrations.AlterField(
            model_name='controller',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
        migrations.AlterField(
            model_name='controllerfile',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=core.utils.get_time.get_mil_sec, null=True),
        ),
    ]
