# Generated by Django 5.0.4 on 2025-04-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0013_alter_tskv_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tskv',
            name='str_v',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='tskvlatest',
            name='str_v',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
