# Generated by Django 5.0.4 on 2025-05-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
        ('shuttle', '0014_alter_tskv_str_v_alter_tskvlatest_str_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tskvlatest',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device'),
        ),
    ]
