# Generated by Django 5.0.4 on 2025-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
        ('shuttle', '0015_alter_tskvlatest_entity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attributekv',
            constraint=models.UniqueConstraint(fields=('entity_type', 'attribute_type', 'entity_id', 'attribute_key'), name='unique_attrkv_type_scope_entity_key'),
        ),
    ]
