# Generated by Django 5.0.4 on 2025-06-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_emailconfiguration_updated_at_and_more'),
        ('shuttle', '0016_attributekv_unique_attrkv_type_scope_entity_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tskvlatest',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ts_kvs_latest', to='main.device'),
        ),
    ]
