# Generated by Django 5.0.4 on 2025-07-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0017_alter_tskvlatest_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tskv',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
