# Generated by Django 5.0.4 on 2025-07-06 23:38

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0018_alter_tskv_options"),
    ]

    operations = [
        CreateExtension("timescaledb"),
        migrations.RunSQL(
            # Forward SQL
            """
            BEGIN;
            CREATE TABLE IF NOT EXISTS shuttle_ts_kv_backup AS SELECT * FROM shuttle_ts_kv;

            -- Drop the id column
            ALTER TABLE shuttle_ts_kv DROP COLUMN IF EXISTS id;

            -- Alter field varchar to text
            ALTER TABLE shuttle_ts_kv ALTER COLUMN str_v TYPE TEXT;


            -- Drop the old primary key
            ALTER TABLE shuttle_ts_kv DROP CONSTRAINT shuttle_ts_kv_entity_id_key_ts_0a191f45_uniq;
            -- ALTER TABLE shuttle_ts_kv DROP CONSTRAINT shuttle_ts_kv_pkey;

            -- Optimize indexes for time-series
            DROP INDEX IF EXISTS shuttle_ts_kv_entity_id_key_ts_0a191f45_uniq;
            DROP INDEX IF EXISTS shuttle_ts_kv_pkey;
            DROP INDEX IF EXISTS shuttle_ts_kv_entity_id_291f3b1d;
            DROP INDEX IF EXISTS shuttle_ts_kv_key_2d803052;

            -- Ensure required columns are NOT NULL
            ALTER TABLE shuttle_ts_kv ALTER COLUMN ts SET NOT NULL;
            ALTER TABLE shuttle_ts_kv ALTER COLUMN key SET NOT NULL;
            ALTER TABLE shuttle_ts_kv ALTER COLUMN entity_id SET NOT NULL;

            -- Create new primary key
            ALTER TABLE shuttle_ts_kv ADD CONSTRAINT shuttle_ts_kv_pkey
            PRIMARY KEY (ts, key, entity_id);

            CREATE INDEX shuttle_ts_kv_entity_id_ts_idx ON shuttle_ts_kv (entity_id, ts DESC);
            CREATE INDEX shuttle_ts_kv_key_ts_idx ON shuttle_ts_kv (key, ts DESC);

            -- Convert to hypertable
            SELECT create_hypertable('shuttle_ts_kv', 'ts', migrate_data => true);

            -- Optional: Set chunk interval
            SELECT set_chunk_time_interval('shuttle_ts_kv', INTERVAL '1 day');

            COMMIT;
            """
        ),
    ]


"""

"""
