# Generated by Django 5.0.4 on 2025-07-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0019_auto_20250706_2338"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tskv",
            options={"managed": False, "ordering": ("ts",)},
        ),
    ]
