# Generated by Django 5.0.4 on 2025-07-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0020_alter_tskv_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tskv",
            options={"managed": False, "ordering": ("-ts",)},
        ),
    ]
