# Generated by Django 5.0.4 on 2025-07-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0021_alter_tskv_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributekv",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("view_attributelist", "Can view attribute lists"),
                    ("add_attributelist", "Can add attribute lists"),
                    ("add_attributerpc", "Can add attribute rpc"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="rpcmessage",
            options={"permissions": [("send_jsonrpc", "Can send json rpc request")]},
        ),
    ]
