# Generated by Django 5.0.4 on 2026-02-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0023_attributekv_created_by_relation_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tskvdictionary",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="tskvdictionary",
            name="key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
