# Generated by Django 5.0.4 on 2026-05-13 05:28

from django.db import migrations, models

_FORWARD_SQL = """
    ALTER TABLE shuttle_controller
        ALTER COLUMN created_at TYPE timestamp with time zone
            USING to_timestamp(created_at / 1000.0),
        ALTER COLUMN updated_at TYPE timestamp with time zone
            USING to_timestamp(updated_at / 1000.0);

    ALTER TABLE shuttle_controller_file
        ALTER COLUMN created_at TYPE timestamp with time zone
            USING to_timestamp(created_at / 1000.0),
        ALTER COLUMN updated_at TYPE timestamp with time zone
            USING to_timestamp(updated_at / 1000.0);
"""

_REVERSE_SQL = """
    ALTER TABLE shuttle_controller
        ALTER COLUMN created_at TYPE bigint
            USING (EXTRACT(EPOCH FROM created_at) * 1000)::bigint,
        ALTER COLUMN updated_at TYPE bigint
            USING (EXTRACT(EPOCH FROM updated_at) * 1000)::bigint;

    ALTER TABLE shuttle_controller_file
        ALTER COLUMN created_at TYPE bigint
            USING (EXTRACT(EPOCH FROM created_at) * 1000)::bigint,
        ALTER COLUMN updated_at TYPE bigint
            USING (EXTRACT(EPOCH FROM updated_at) * 1000)::bigint;
"""

class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0024_alter_tskvdictionary_unique_together_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_FORWARD_SQL, reverse_sql=_REVERSE_SQL),
            ],
            state_operations=[
                migrations.AlterField(model_name="controller", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
                migrations.AlterField(model_name="controller", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
                migrations.AlterField(model_name="controllerfile", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
                migrations.AlterField(model_name="controllerfile", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="controller",
            options={},
        ),
        migrations.AlterModelOptions(
            name="controllerfile",
            options={},
        ),
    ]
