# Generated by Django 5.0.4 on 2026-06-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0025_alter_controller_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tskvlatest",
            name="str_v",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE shuttle_ts_kv ALTER COLUMN str_v TYPE text",
            reverse_sql="ALTER TABLE shuttle_ts_kv ALTER COLUMN str_v TYPE varchar(10000)",
        ),
    ]
