# Generated by Django 5.0.4 on 2026-07-21 05:36

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY нельзя выполнять внутри транзакции, поэтому миграция
    # неатомарна. Это позволяет не брать блокировку на запись в горячую таблицу
    # shuttle_attribute_kv (в неё пишет каждый telemetry/attributes/state-батч).
    atomic = False

    dependencies = [
        ('main', '0064_alter_deviceprofile_image'),
        ('shuttle', '0026_alter_tskv_str_v_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekv',
            name='str_v',
            field=models.TextField(blank=True, null=True),
        ),
        AddIndexConcurrently(
            model_name='attributekv',
            index=models.Index(fields=['entity_id', 'attribute_type', 'attribute_key'], name='ix_attrkv_entity_type_key'),
        ),
    ]
