# Generated by Django 5.0.4 on 2026-09-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_tenant_options'),
        ('shuttle', '0027_alter_attributekv_str_v_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tskvlatest',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_kvs_latest', to='main.device'),
        ),
        migrations.AddIndex(
            model_name='tskvlatest',
            index=models.Index(fields=['key'], name='ix_ts_kv_latest_key'),
        ),
    ]
