# Generated by Django 5.0.4 on 2024-05-08 11:02

import core.utils.unix_timestamp
import django.db.models.deletion
import time
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='updated_at',
            field=core.utils.unix_timestamp.UnixTimeStampField(default=time.time, null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
