# Generated by Django 5.0.4 on 2024-07-06 10:33

import core.utils.unix_timestamp
import django.db.models.deletion
import time
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_room_status_dashboard_roomtype_dashboard_widgettype"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCredentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    core.utils.unix_timestamp.UnixTimeStampField(
                        default=time.time, editable=False, null=True
                    ),
                ),
                (
                    "credentials_id",
                    models.CharField(blank=True, null=True, unique=True),
                ),
                (
                    "credentials_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("credentials_value", models.CharField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.device",
                    ),
                ),
            ],
            options={
                "db_table": "main_device_credentials",
            },
        ),
    ]
