# Generated by Django 5.0.4 on 2024-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_devicecredentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfiguration",
            name="frontend_host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="frontend_port",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
