# Generated by Django 5.0.4 on 2024-10-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_roomhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'floor', 'block')},
        ),
    ]
