# Generated by Django 5.0.4 on 2024-11-22 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_guest_additional_info_guest_language_guest_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'floor', 'block', 'tenant')},
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'CheckedIn'), (2, 'Occupied'), (3, 'DoNotDisturb'), (4, 'MakeUpRoom')]), size=None),
        ),
    ]
