# Generated by Django 5.0.4 on 2024-11-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_device_name_alter_device_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('title', 'tenant')},
        ),
    ]
