# Generated by Django 5.0.4 on 2024-12-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_dashboard_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'tenant', 'is_active')},
        ),
    ]
