# Generated by Django 5.0.4 on 2025-01-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_room_unique_together_room_unique_active_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='main.dashboard'),
        ),
    ]
