# Generated by Django 5.0.4 on 2025-01-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_room_state_alter_roomhistory_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceprofile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='deviceprofile',
            unique_together={('name', 'tenant')},
        ),
    ]
